version: "3.8"

services:
  app:
    image: registry.gitlab.com/q347/starlette_down_pinterest:v0.2
    container_name: none_backend
    command: gunicorn --worker-class=uvicorn.workers.UvicornWorker --log-level warning --worker-connections=1000 --workers=3 --bind 0.0.0.0:8000 app:app
    environment:
      VIRTUAL_HOST: linhtools2.13net.xyz
      VIRTUAL_PORT: 8000
    restart: unless-stopped
    volumes:
      - ./app:/app
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
networks:
  default:
    external:
      name: b_nginx_network
